### ISSUE TITLE
Install Script mounts non-existent memory device on non-jetson computers

### ISSUE THREAD

**Issue by John-Ellis** [John-Ellis/derplearning#11]
install/install.sh currently mounts a spare memory device on the partition it's run on regardless of whether the device has that memory device. This prevents such devices from rebooting sucessfully.

**Comment by notkarol** [comment]
``if [[ $(uname -m) -eq "aarch64" ]] ; then bash sdcard.sh ``
Should not run if you're on an AMD64 machine. I'll put in a check for it just in case someone inadvertantly runs sdcard.sh
